spec-version: 0.36.0
name: ghc-hie

copyright: (c) 2025 Simon Hengel
author: Simon Hengel <sol@typeful.net>

ghc-options: -Wall

language: GHC2021

dependencies:
  - base
  - bytestring
  - containers
  - deepseq
  - array
  - transformers
  - filepath
  - directory
  - ghc == { 9.10.1, 9.10.2, 9.12.1 }
  - ghc-boot

source-dirs: src

library:
  exposed-modules:
    - GHC.Iface.Ext.Binary
    - GHC.Iface.Ext.Debug
    - GHC.Iface.Ext.Types
    - GHC.Iface.Ext.Utils

tests:
  spec:
    build-tools: hspec-discover
    main: Spec.hs
    source-dirs:
      - test
    dependencies:
      - hspec == 2.*
      - process
      - temporary
