spec-version: 0.36.0

name: ghc-hie
version: 0.0.1
synopsis: HIE-file parsing machinery that supports multiple versions of GHC
copyright: (c) 2025 Simon Hengel
author: Simon Hengel <sol@typeful.net>
category: Development

github: sol/ghc-hie

ghc-options: -Wall -O2

language: GHC2021

dependencies:
  - base == 4.*
  - bytestring
  - containers
  - deepseq
  - array
  - transformers
  - filepath
  - directory
  - ghc == { 9.8.4, 9.10.1, 9.10.2, 9.12.1, 9.12.2 }
  - ghc-boot

source-dirs: src

library:
  exposed-modules:
    - GHC.Iface.Ext.Binary
    - GHC.Iface.Ext.Debug
    - GHC.Iface.Ext.Types
    - GHC.Iface.Ext.Utils

tests:
  spec:
    build-tools: hspec-discover
    main: Spec.hs
    source-dirs:
      - test
    dependencies:
      - hspec == 2.*
      - QuickCheck
      - process
      - temporary
