spec-version: 0.36.0
name: ghc-hie

copyright: (c) 2025 Simon Hengel
author: Simon Hengel <sol@typeful.net>

ghc-options: -Wall

language: GHC2021

dependencies:
  - base
  - bytestring
  - containers
  - deepseq
  - array
  - transformers
  - filepath
  - directory
  - ghc
  - ghc-boot

source-dirs: src

library: {}

tests:
  spec:
    build-tools: hspec-discover
    main: Spec.hs
    source-dirs:
      - test
      - src
    dependencies:
      - hspec == 2.*
      - process
      - temporary
